DefaultContentLanguage = "es"
baseURL = ""
disableAliases = true
enableRobotsTXT = true
languageCode = "es"
title = "Waldorf Pucon"
[languages.en]
contentDir = "content/english"
languageName = "Espanol"
title = "Waldorf School"
weight = 2
[languages.es]
contentDir = "content/spanish"
languageName = "Espanol"
title = "Escuela Waldorf"
weight = 1
[languages.es.params]
linkedin = "https://linkedin.com/whoever"
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
[params]
cloudinary_url = "https://res.cloudinary.com/dz6jcn6n7/image/upload"
disallow_search_engines = false
